process = [
    "Pillow",
    "PyMuPDF",
    "Unidecode",
    "clean-text",
    "docx2pdf",
    "lxml_html_clean",
    "python-docx",
    "python-pptx",
    "clean-text",
    "requests==2.28.1",
    "selenium==4.27.1",
    "surya-ocr>=0.8.3",
    "xlrd==2.0.1",
    "py7zr==0.22.0",
    "rarfile==4.2",
    "markdown==3.7",
    "markdownify>=0.13.1",
    "marker-pdf==1.6.0",
    "moviepy==2.1.1",
    "openpyxl==3.1.5",
    "chonkie==0.2.1.post1",
    "langdetect>=1.0.9",
    "trafilatura==1.4.0",
    "datatrove[processing]",
    "validators==0.34.0",
    "bokeh",
    "motor==3.6.0",
    "fastapi[standard]",
    "fastapi==0.115.5",
    "pydantic== 2.10.4",
    "pymongo==4.9.2"
]

rag = [
  "langchain==0.2.17",
  "langchain-milvus==0.1.7",
  "langchain-huggingface==0.0.3",
  "langchain-openai==0.1.20",
  "langchain-anthropic==0.1.23",
  "langchain-mistralai==0.1.13",
  "langchain-cohere==0.2.4",
  "langchain-nvidia-ai-endpoints",
  "langchain-aws",
  "langserve[all]==0.2.3",
  "pymilvus[model]==2.5.0",
  "ragas==0.2.6",
  "nltk>=3.9",
]

all2 = sorted(set(process) | set(rag))
#print('all = [\n' + "\n".join(f'\t"{x}",' for x in all) + "\n]")

all = [
    "Pillow",
    "PyMuPDF",
    "Unidecode",
    "clean-text",
    "docx2pdf",
    "lxml_html_clean",
    "python-docx",
    "python-pptx",
    "clean-text",
    "requests==2.28.1",
    "selenium==4.27.1",
    "surya-ocr==0.6.13",
    "xlrd==2.0.1",
    "py7zr==0.22.0",
    "rarfile==4.2",
    "markdown==3.7",
    "markdownify==0.14.1",
    "marker-pdf==1.6.0",
    "moviepy==2.1.1",
    "openpyxl==3.1.5",
    "chonkie==0.2.1.post1",
    "langdetect>=1.0.9",
    "trafilatura==1.4.0",
    "langchain==0.2.17",
    "langchain-milvus==0.1.7",
    "langchain-huggingface==0.0.3",
    "langchain-openai==0.1.20",
    "langchain-anthropic==0.1.23",
    "langchain-mistralai==0.1.13",
    "langchain-cohere==0.2.4",
    "langchain-nvidia-ai-endpoints",
    "langchain-aws",
    "langserve[all]==0.2.3",
    "pymilvus[model]==2.5.0",
    "ragas==0.2.6",
    "nltk>=3.9",
    "validators==0.34.0",
    "datatrove[processing]"
]

print(set(all) - set(all2))
